### PR TITLE
Custom interpolators by resource Id

### PR DESCRIPTION
**Pull request by aconsuegra**
I have added the ability to choose custom interpolators (from the platform or defined by the user). 
If no interpolator is defined, the library uses the ones you guys have chosen as default.

Do you want me to edit the sample?

### CODE REVIEW

**Comment by pedrovgs** [comment]
Thanks for your PR Antonio!!!! Can you modify one of the current samples to use your feature? The one with the gamepad could be a good choice :). Remember to update the README.md with information about this new attributes.

**Comment by aconsuegra** [comment]
I forgot about the README.md, sorry. I hope it is fine now :)

**Comment by pedrovgs** [comment]
Thanks for your PR @aconsuegra!! We are going to wait for Jorge's review, but to me this is ready to merge and release :) :+1: 

@flipper83 can you review this? I need another +1 to merge this PR.

**Comment by flipper83** [comment]
:+1: thank you Antonio!!!! I will send you a  maxiboom to berlin. :ice_cream:

**Comment by pedrovgs** [comment]
@aconsuegra do you need this feature in production now? Or can we release it with the next PR?

**Pull request merged**
